# Generated by Django 5.2 on 2025-07-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=20)),
                ('batch', models.IntegerField()),
                ('password', models.CharField(max_length=35)),
                ('re_password', models.CharField(max_length=35)),
                ('textarea', models.CharField(max_length=150)),
            ],
        ),
    ]
